apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  namespace: tagliaferrodev
spec:
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: dritoferro/rotten-potatoes
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_DB
              value: admin
            - name: MONGODB_HOST
              value: admin
            - name: MONGODB_USERNAME
              value: mongouser
            - name: MONGODB_PASSWORD
              value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: movies-service
  namespace: tagliaferrodev
spec:
  selector:
    app: movies
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort